### ISSUE TITLE
Install fails - repo still maintained?

### ISSUE THREAD

**Issue by loleg** [6aika/open-city-skeleton#1]
Following the fork-branch-install steps in the readme, you get this error:

```
$ npm install
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/haltu/open-city-modules.git
npm ERR! 
npm ERR! ERROR: Repository not found.
```

**Comment by spjass** [comment]
The open-city-modules dependency in package.json seems to have been pointing to a wrong repository. 

Fixed in https://github.com/6aika/open-city-skeleton/commit/75750bfbb0c134986c5bb6cb5be825fd8ce45ec1

**Comment by loleg** [comment]
It worked. Thank you!
